// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtS1VoZNL15RSKiIeOz0TkBR9iZfyG7qY',
    appId: '1:1009986057061:web:d94e81c1eb1665fb2fa78c',
    messagingSenderId: '1009986057061',
    projectId: 'flutter-chat-app-6bf2a',
    authDomain: 'flutter-chat-app-6bf2a.firebaseapp.com',
    storageBucket: 'flutter-chat-app-6bf2a.appspot.com',
    measurementId: 'G-HK3NPCY6R8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBht_iGtyjwsTCqcG08pWX1lCm8sqwuPPI',
    appId: '1:1009986057061:android:dcd01dbb5a2e51bc2fa78c',
    messagingSenderId: '1009986057061',
    projectId: 'flutter-chat-app-6bf2a',
    storageBucket: 'flutter-chat-app-6bf2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXciSocWE7c36rYsIcRJ7MPoaL4gdzKMo',
    appId: '1:1009986057061:ios:be3cd08f5286cd3c2fa78c',
    messagingSenderId: '1009986057061',
    projectId: 'flutter-chat-app-6bf2a',
    storageBucket: 'flutter-chat-app-6bf2a.appspot.com',
    iosClientId: '1009986057061-04gae69sfaioj52ei2829orqp6cip2qs.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXciSocWE7c36rYsIcRJ7MPoaL4gdzKMo',
    appId: '1:1009986057061:ios:be3cd08f5286cd3c2fa78c',
    messagingSenderId: '1009986057061',
    projectId: 'flutter-chat-app-6bf2a',
    storageBucket: 'flutter-chat-app-6bf2a.appspot.com',
    iosClientId: '1009986057061-04gae69sfaioj52ei2829orqp6cip2qs.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApp',
  );
}
